# Generated by Django 6.0.7 on 2026-07-19 19:18

import django.db.models.deletion
import resumes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(help_text='Upload your resume (PDF only, max 5MB)', upload_to='resumes/', validators=[resumes.validators.validate_pdf_file])),
                ('title', models.CharField(blank=True, default='My Resume', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
