# Generated by Django 6.0.7 on 2026-07-19 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='e.g., Senior Software Engineer', max_length=255)),
                ('experience', models.TextField(blank=True, default='', help_text='Years or description of experience')),
                ('education', models.TextField(blank=True, default='', help_text='Education background')),
                ('skills', models.TextField(blank=True, default='', help_text='Comma-separated list of skills')),
                ('portfolio_link', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidate',
                'verbose_name_plural': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
